version: 2
updates:
  - package-ecosystem: "docker-compose"
    directory: "/tests/integration"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 1
    groups:
      docker-compose-tests:
        patterns:
          - "*"
