name: "Push images to Docker Hub"
on: workflow_dispatch
jobs:
  build:
    name: "Build and push images"
    runs-on: "ubuntu-24.04"
    steps:
      - name: "Check out repository"
        uses: "actions/checkout@v4"
      - name: "Set up buildx"
        uses: "docker/setup-buildx-action@v3"
      - name: "Log in to Docker Hub"
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - name: "Build and push Storage Service"
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          load: true
          file: ./Dockerfile
          target: "archivematica-storage-service"
          tags: artefactual/archivematica-storage-service:latest
